name: Build LaTeX document
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Download fonts
        run: |
          curl -OL https://github.com/adobe-fonts/source-han-serif/releases/download/2.003R/07_SourceHanSerifJ.zip
          curl -OL https://github.com/adobe-fonts/source-han-serif/releases/download/2.003R/09_SourceHanSerifSC.zip
          7z x 07_SourceHanSerifJ.zip OTF/Japanese
          7z x 09_SourceHanSerifSC.zip OTF/SimplifiedChinese
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: lyrics.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ./OTF/SimplifiedChinese/*.otf
            ./OTF/Japanese/*.otf
      - name: Prepare dir
        run: |
          mkdir www
          mv lyrics.pdf www
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: www

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build_latex

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
